<?php

return [
  'app_name' => 'SIKessEm',
  'app_base' => '/',
  'app_scheme' => 'https',
  'app_host' => 'sikessem.test',
  'app_author' => '<? author_name ?>',
  'author_firstname' => 'Kessé Emmanuel',
  'author_lastname' => 'SIGUI',
  'author_fullname' => '<? author_lastname ?> <? author_firstname ?>',
  'author_shortname' => 'SIKessEm',
  'author_name' => '<? author_shortname ?> (<? author_fullname ?>)',
  'author_github' => 'https://github.com/SIKessEm/',
  'author_packagist' => 'https://packagist.org/packages/sikessem/',
  'author_npmjs' => 'https://npmjs.com/~sikessem/',
  'author_linkedin' => 'https://linkedin.com/in/SIKessEm/',
  'author_twitter' => 'https://twitter.com/SIKessEm_tweets/',
  'author_facebook' => 'https://facebook.com/SIKessEm/',
  'author_instagram' => 'https://instagram.com/SIKessEm/',
  'author_youtube' => 'https://www.youtube.com/channel/UCBMF8GBqu-Bab6ib4j9yGnQ/',
  'author_pinterest' => 'https://pinterest.com/SIKessEm/',
  'author_whatsapp' => 'https://wa.me/21656404791/',
  'author_email' => 'sikessem@omninf.com',
];
