#!/usr/bin/php
<?php
use Start\Core;

require __DIR__ . '/init.php';

$options = (array) @require __DIR__ . '/cfg/program.php';
$core = new Core(ROOT_DIR, $options);

echo 'Welcome to '. $core->app_name .' CLI !' . PHP_EOL;
echo 'Code executed in '. $core->time() . 'ms';
exit;
